"""Hermes adapter. Mounts the operator context into ~/.hermes as a managed
OPERATOR.md file, and writes a one-shot SOUL.md loader if missing.
"""
from __future__ import annotations

from .. import cli as _cli


GOVERNANCE_HEADER = (
    "# cognitive-os Governance Declaration\n\n"
    "You are operating under the **cognitive-os** governance system.\n\n"
    "cognitive-os is the authoritative identity and reasoning layer above any agent platform. "
    "It defines who you are, how you think, and what constraints govern your actions — "
    "regardless of which platform is running you.\n\n"
    "The cognitive profile, workflow policy, and memory contracts below are not suggestions. "
    "They define how you are required to think and act.\n\n"
    "The agent platform (Claude Code, Hermes, or any other) is the delivery vessel. "
    "cognitive-os is the governing soul.\n\n"
    "---\n\n"
)

_MEMORY_FILES = ["overview.md", "operator_profile.md", "workflow_policy.md", "cognitive_profile.md"]


def _compose_operator_context() -> str:
    sections: list[str] = [
        "# Operator Context\n\n"
        "Generated by `cognitive-os sync`. "
        "Edit sources in `~/cognitive-os/core/memory/global/`.\n\n",
        GOVERNANCE_HEADER,
    ]
    for name in _MEMORY_FILES:
        mem_file = _cli.REPO_ROOT / "core" / "memory" / "global" / name
        if mem_file.exists():
            sections.append(mem_file.read_text(encoding="utf-8").rstrip() + "\n\n")
    return "".join(sections).rstrip()


def sync() -> bool:
    """Sync operator context + skills into ~/.hermes if installed.

    Returns True if Hermes was found and synced, False if not installed.
    """
    hermes_root = _cli.HOME / ".hermes"
    if not hermes_root.exists():
        return False

    skills_dst = hermes_root / "skills"
    for skill_dir in _cli._managed_skills():
        _cli._copy_tree(skill_dir, skills_dst / skill_dir.name)

    operator_md = hermes_root / "OPERATOR.md"
    _cli._write_managed_file(
        operator_md,
        _compose_operator_context(),
        prior_signature="# Operator Context",
    )

    soul_path = hermes_root / "SOUL.md"
    if not soul_path.exists():
        soul_content = (
            "# Hermes Soul\n\n"
            "You are a technical AI assistant working with the operator described below.\n"
            "Load this context at the start of every session.\n\n"
            f"{{{{read {operator_md}}}}}\n"
        )
        _cli._write_text(soul_path, soul_content)
        print(f"  - Created Hermes SOUL.md: {soul_path}")

    return True


__all__ = ["sync", "GOVERNANCE_HEADER", "_compose_operator_context"]
